id: IABFAF1CE
source: https://sakyaresearch.org
source_file: null
initial_creation_type: input
imported: '2022-06-18T20:37:45.016995'
last_modified: '2022-06-18T20:37:45.017006'
parser: null
source_metadata:
  title: Fundamentals of Turning the Wheel of Dharma
  author: གསེར་མདོག་པཎ་ཆེན་ཤཱཀྱ་མཆོག་ལྡན།
  description: 'Digital version 4.0 {Tibetan}; master xml (completed: 2012-09); linebreaks
    encoded, revision in process, no thematic TEI markup'
  file_info:
  - 'Language: Tibetan'
  - 'Coverage: Full Text'
  - 'Accessible: publicly'
  responibilities:
  - Digital edition:ས་སྐྱ་ཞིབ་འཇུག་ཁང་། (src)
  - Text input:Volker Caumanns (vc)
  - Editorial process:Volker Caumanns (vc), Mathias Fermer (mf)
  - TEI Encoding:ས་སྐྱ་ཞིབ་འཇུག་ཁང་།
  - TEI Markup:-
  - Revisions/Corrections:Volker Caumanns (vc)
  text_witnesses: https://sakyaresearch.org/sources/132
  bases:
    2e37:
      title: Fundamentals of Turning the Wheel of Dharma
      order: 1
      base_file: 2e37.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
